name: Build iOS App
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4  # Actualizado de v3 a v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Actualizado de v4 a v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install buildozer
          pip install kivy-ios
          brew install autoconf automake libtool pkg-config cmake

      - name: Build with Buildozer
        run: buildozer ios debug
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # ¡Esta es la corrección clave! v3 -> v4
        with:
          name: iOS-App
          path: bin/*.ipa
